[project]
name = "sentimental-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "joblib>=1.5.3",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "optuna>=4.9.0",
    "pandas>=3.0.5",
    "scikit-learn==1.8.0",
    "xgboost>=3.3.0",
]
